#if UNITY_EDITOR
using System.Collections.Generic;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.Rendering.Universal;

/// <summary>
/// One-click setup for the Janitor movement prototype:
/// builds a standalone JanitorPrototype scene (camera + global light + floor +
/// Janitor instance) so the Janitor can be playtested on its own device/scene
/// without the Killer/Detective scene. Run via:
/// Tools > Game Jam > Setup Janitor Prototype Scene.
/// Reuses the sprite and Janitor.prefab generated by KillerPrototypeSetup;
/// re-running is safe, the scene is regenerated.
/// </summary>
public static class JanitorPrototypeSetup
{
    private const string SpritePath = "Assets/Art/Prototype/WhiteSquare.png";
    private const string JanitorPrefabPath = "Assets/Prefabs/Prototype/Janitor.prefab";
    private const string BloodPrefabPath = "Assets/Prefabs/Prototype/Blood.prefab";
    private const string CorpsePrefabPath = "Assets/Prefabs/Prototype/Corpse.prefab";
    private const string ScenePath = "Assets/Scenes/JanitorPrototype.unity";

    [MenuItem("Tools/Game Jam/Setup Janitor Prototype Scene")]
    public static void Setup()
    {
        Sprite square = AssetDatabase.LoadAssetAtPath<Sprite>(SpritePath);
        Debug.Assert(square != null, $"Missing sprite at {SpritePath} — run 'Setup Killer Prototype Scene' once first.");

        GameObject janitorPrefab = AssetDatabase.LoadAssetAtPath<GameObject>(JanitorPrefabPath);
        Debug.Assert(janitorPrefab != null, $"Missing prefab at {JanitorPrefabPath} — run 'Setup Killer Prototype Scene' once first.");

        GameObject bloodPrefab = AssetDatabase.LoadAssetAtPath<GameObject>(BloodPrefabPath);
        Debug.Assert(bloodPrefab != null, $"Missing prefab at {BloodPrefabPath} — run 'Setup Killer Prototype Scene' once first.");

        EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo();
        EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

        // Camera (same look as KillerPrototype)
        var cameraGo = new GameObject("Main Camera");
        Camera camera = cameraGo.AddComponent<Camera>();
        camera.tag = "MainCamera";
        camera.orthographic = true;
        camera.orthographicSize = 7f;
        camera.clearFlags = CameraClearFlags.SolidColor;
        camera.backgroundColor = new Color(0.1f, 0.1f, 0.12f);
        cameraGo.transform.position = new Vector3(0f, 0f, -10f);
        cameraGo.AddComponent<UniversalAdditionalCameraData>();

        // Global 2D light (URP)
        var lightGo = new GameObject("Global Light 2D");
        Light2D light = lightGo.AddComponent<Light2D>();
        light.lightType = Light2D.LightType.Global;
        light.intensity = 1f;

        // Floor (placeholder room, same as KillerPrototype)
        var floor = new GameObject("Floor");
        SpriteRenderer floorRenderer = floor.AddComponent<SpriteRenderer>();
        floorRenderer.sprite = square;
        floorRenderer.color = new Color(0.42f, 0.4f, 0.36f);
        floorRenderer.sortingOrder = -10;
        floor.transform.localScale = new Vector3(26f, 16f, 1f);
        floor.transform.position = Vector3.zero;

        // Janitor (movement + blood cleaning + corpse drag prototype)
        GameObject janitor = (GameObject)PrefabUtility.InstantiatePrefab(janitorPrefab);
        janitor.transform.position = Vector3.zero;

        // Wire the cleanup interaction onto the instance (prefab stays untouched).
        JanitorCleanup cleanup = janitor.AddComponent<JanitorCleanup>();
        SetField(cleanup, "input", janitor.GetComponent<JanitorInput>());

        // Corpse drag + disposal zone (disposalZone wired after it is created).
        JanitorCorpseDrag corpseDrag = janitor.AddComponent<JanitorCorpseDrag>();
        SetField(corpseDrag, "input", janitor.GetComponent<JanitorInput>());
        SetField(cleanup, "drag", corpseDrag);

        JanitorDebugHud hud = janitor.AddComponent<JanitorDebugHud>();
        SetField(hud, "movement", janitor.GetComponent<JanitorMovement>());
        SetField(hud, "cleanup", cleanup);
        SetField(hud, "corpseDrag", corpseDrag);

        // Test Blood instances (runtime evidence normally spawned by the Killer).
        // One inside interaction range (~1.3 m), one outside (~2.7 m) for range testing.
        Object.Instantiate(bloodPrefab, new Vector3(1.2f, 0.5f, 0f), Quaternion.identity);
        Object.Instantiate(bloodPrefab, new Vector3(2.5f, -1f, 0f), Quaternion.identity);

        // Test Corpse instances (runtime evidence normally spawned by the Killer).
        // One near the Janitor start, one near the disposal zone for drag testing.
        GameObject corpsePrefab = AssetDatabase.LoadAssetAtPath<GameObject>(CorpsePrefabPath);
        Debug.Assert(corpsePrefab != null, $"Missing prefab at {CorpsePrefabPath} — run 'Setup Killer Prototype Scene' once first.");
        Object.Instantiate(corpsePrefab, new Vector3(-2f, 1.5f, 0f), Quaternion.identity);
        Object.Instantiate(corpsePrefab, new Vector3(6f, -2f, 0f), Quaternion.identity);

        // DisposalZone: green trigger area. Dragged corpses are disposed instantly
        // on entry; corpses that are not being dragged have no effect here.
        var zoneGo = new GameObject("DisposalZone");
        SpriteRenderer zoneRenderer = zoneGo.AddComponent<SpriteRenderer>();
        zoneRenderer.sprite = square;
        zoneRenderer.color = new Color(0.2f, 0.8f, 0.35f, 0.8f);
        zoneRenderer.sortingOrder = -5;
        zoneGo.transform.position = new Vector3(10f, -5f, 0f);
        zoneGo.transform.localScale = new Vector3(3f, 3f, 1f);
        BoxCollider2D zoneCollider = zoneGo.AddComponent<BoxCollider2D>();
        zoneCollider.isTrigger = true;
        SetColliderField(corpseDrag, "disposalZone", zoneCollider);

        EditorSceneManager.SaveScene(EditorSceneManager.GetActiveScene(), ScenePath);

        // Build settings: keep existing entries and append the Janitor scene.
        var buildScenes = new List<EditorBuildSettingsScene>(EditorBuildSettings.scenes);
        if (!buildScenes.Exists(s => s.path == ScenePath))
        {
            buildScenes.Add(new EditorBuildSettingsScene(ScenePath, true));
        }

        EditorBuildSettings.scenes = buildScenes.ToArray();

        Debug.Log("[JanitorPrototypeSetup] Done. Open 'Assets/Scenes/JanitorPrototype.unity' and press Play. " +
                  "Controls: WASD/Arrows to move (5 m/s), E near Blood to clean (1.75 m, 5 s; moving cancels), " +
                  "E near Corpse to drag (2.5 m/s; E again to drop), carry a dragged Corpse into the green DisposalZone to dispose it.");
    }

    private static void SetField(Object obj, string fieldName, object value)
    {
        var so = new SerializedObject(obj);
        so.FindProperty(fieldName).objectReferenceValue = (Object)value;
        so.ApplyModifiedPropertiesWithoutUndo();
    }

    private static void SetColliderField(Object obj, string fieldName, Collider2D value)
    {
        var so = new SerializedObject(obj);
        so.FindProperty(fieldName).objectReferenceValue = value;
        so.ApplyModifiedPropertiesWithoutUndo();
    }
}
#endif
